<p>1. Write a function so that the columns of the output matrix are powers of the input
vector.
    
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.</p>

In [15]:
import numpy as np

In [16]:
def gen_mat(ipvector, n, increasing=True):
    if increasing:
        opmat = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif not increasing:
        opmat = np.array([x**(n-i-1)for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    return opmat

In [19]:
input_vec = np.array([1,2,3,4,5])
no_col = 3
op_mat_inc = gen_mat(input_vec, no_col, True)
op_mat_dec = gen_mat(input_vec, no_col, False)

print("Input Matrix is:\n",input_vec)
print("No of columns in the ouput matrix:\n",no_col)
print("Generated output matrix in the increasing order of powers:\n",op_mat_inc)
print("Generated output matrix in the decreasing order of powers:\n",op_mat_dec)

Input Matrix is:
 [1 2 3 4 5]
No of columns in the ouput matrix:
 3
Generated output matrix in the increasing order of powers:
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
Generated output matrix in the decreasing order of powers:
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


<h3>PROBLEM STATEMENT</h3>
<p>Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below<br>
i 1 2 3 4 5 6 7 8 9 10 <br>
===== == == == == == == == == == ==<br>
Input 10 20 30 40 50 60 70 80 90 100<br>
y1 25 = (10+20+30+40)/4<br>
y2 35 = (20+30+40+50)/4<br>
y3 45 = (30+40+50+60)/4<br>
y4 55 = (40+50+60+70)/4<br>
y5 65 = (50+60+70+80)/4<br>
y6 75 = (60+70+80+90)/4<br>
y7 85 = (70+80+90+100)/4<br>
Thus, the moving average sequence has n-k+1=10-4+1=7 values.</p></br>
<p>Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.</p>

In [20]:
import numpy as np

In [40]:
def mov_avg(arr, win_size):
    return np.convolve(arr, np.ones(win_size),'valid')/win_size
data = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
print("The moving average of the sequence ",data,"is:\n")
print(mov_avg(data,3))

The moving average of the sequence  [  3   5   7   2   8  10  11  65  72  81  99 100 150] is:

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
